test_1/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/category', 'CategoryController');
Route::resource('/product', 'ProductController');

test_1/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',    
        'price',    
        'description',    
        'status',    
        'profile',    
        'category_id'  
    ];
}

test_1/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Image;
use File;
use App\Product;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $records=Product::join('categories','categories.id','=','products.category_id')
            ->select(['products.*','categories.name as cate_name'])
            ->paginate(2);
        return view('product.index',compact('records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['category']=Category::all();
        return view('product.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $request->status = $request->has('status')?1:0;
        $request->validate([
            'name'=>'required|unique:products',
            'price'=>'required|numeric',
            'description'=>'required',
            'filename' => 'image|mimes:jpeg,png,jpg,gif,svg',
            'category_id'=>'required|numeric'
        ]);
        $product = new Product($request->all());
        $product->status = $request->status;

        // image 
        if($request->hasFile('profile')) {
            $originalImage= $request->file('profile');
            $fileName = date('Ymdhis').'_'.Auth()->user()->id.'.'.$originalImage->getClientOriginalExtension();
            $thumbnailImage = Image::make($originalImage);
            $thumbnailPath = public_path().'/images/product/thumbnail/';
            $originalPath = public_path().'/images/product/';
            $thumbnailImage->save($originalPath.$fileName);
            $thumbnailImage->resize(50,50);
            $thumbnailImage->save($thumbnailPath.$fileName); 

            $product->profile = $fileName;
		}else{
            $product->profile = 'blank.png';
        }
        $product->save();
        return redirect('/product')->with('success', $request->name.' saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $data['category']=Category::all();
        return view('product.edit', compact('product'))->with($data);  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {   

        $request->status = $request->has('status')?1:0;
        $request->validate([
            'name'=>'required|'.Rule::unique('products')->ignore($product->id),
            'price'=>'required|numeric',
            'description'=>'required',
            'category_id'=>'required|numeric'
        ]);

        // image 
        if($request->hasFile('profile')) {
            $originalImage= $request->file('profile');
            $fileName = date('Ymdhis').'_'.Auth()->user()->id.'.'.$originalImage->getClientOriginalExtension();
            $thumbnailImage = Image::make($originalImage);
            $thumbnailPath = public_path().'/images/product/thumbnail/';
            $originalPath = public_path().'/images/product/';
            $thumbnailImage->save($originalPath.$fileName);
            $thumbnailImage->resize(50,50);
            $thumbnailImage->save($thumbnailPath.$fileName); 

            // after upload delete old image 
            $thumbnailPath = public_path().'/images/product/thumbnail/'.$product->profile;
            $originalPath = public_path().'/images/product/'.$product->profile;
            if(File::exists($thumbnailPath) && $product->profile!='blank.png'){
                File::delete($thumbnailPath);
            }
            if(File::exists($originalPath)){
                File::delete($originalPath);
            }

            $fileName = $fileName;
		}else{
            $fileName = $request->get('old_profile');
        }
        
        $product->update([
            'name' => $request->get('name'),
            'price' => $request->get('price'),
            'description' => $request->get('description'),
            'profile' => $fileName,
            'category_id' => $request->get('category_id'),
            'status' => $request->status
        ]);
        return redirect('/product')->with('success', $product->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {   
        $thumbnailPath = public_path().'/images/product/thumbnail/'.$product->profile;
        $originalPath = public_path().'/images/product/'.$product->profile;
        if(File::exists($thumbnailPath) && $product->profile!='blank.png'){
            File::delete($thumbnailPath);
        }
        if(File::exists($originalPath)){
            File::delete($originalPath);
        }
        


        $product->delete();
        return redirect('/product')->with('success', 'deleted!');
    }
}

test_1/resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Add Product Page</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                    @endif
                    <form action="{{ route('product.store') }}" method="post" autocomplete="off" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="name">Product Name:</label>
                                    <input type="text" name="name" class="form-control {{ $errors->has('name')?'red_border':'' }}" id="name" value="{{ old('name') }}">
                                </div>
                                <div class="form-group">
                                    <label for="price">Price:</label>
                                    <input type="number" name="price" class="form-control {{ $errors->has('price')?'red_border':'' }}" id="price" value="{{ old('price') }}">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description:</label>
                                    <input type="text" name="description" class="form-control {{ $errors->has('description')?'red_border':'' }}" id="description" value="{{ old('description') }}">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="form-group">
                                            <label for="profile">Profile:</label>
                                            <input type="file" name="profile" class="form-control" onchange="readURL(this);" id="profile" value="{{ old('profile') }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="category">Category:</label>
                                            <select name="category_id" class="form-control {{ $errors->has('category_id')?'red_border':'' }}" id="category">
                                                <option value="">please choose</option>
                                                @foreach($category as $data)
                                                    <option {{ old('category_id')==$data->id?'selected':'' }} value="{{ $data->id }}">{{ $data->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <img width="100%" id="profile-img-tag" src="/images/product/thumbnail/blank.png" alt="" >
                                    </div>
                                </div>
                                <div class="form-group">
                                    <br>
                                    <br>
                                    <input type="checkbox" name="status" id="status" {{ old('status')=="on"?'checked':'' }}>
                                    <label for="status">Status</label>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('product.index') }}" class="btn btn-danger"> Back</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@endsection

test_1/resources/views/product/edit.blade.php
@extends('layouts.app')
 
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit Product Page</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div><br />
                    @endif
                    <form action="{{ route('product.update',$product->id) }}" method="post" enctype="multipart/form-data">
                        @method('PATCH')
                        @csrf
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label for="name">Product Name:</label>
                                    <input type="text" name="name" class="form-control" id="name" value="{{ $product->name }}">
                                </div>
                                <div class="form-group">
                                    <label for="price">Price:</label>
                                    <input type="text" name="price" class="form-control" id="price" value="{{ $product->price }}">
                                </div>
                                <div class="form-group">
                                    <label for="description">Description:</label>
                                    <input type="text" name="description" class="form-control" id="description" value="{{ $product->description }}">
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="form-group">
                                            <label for="profile">Profile:</label>
                                            <input type="file" name="profile" class="form-control"  onchange="readURL(this);" id="profile" value="{{ old('profile') }}">
                                            <input type="hidden" name="old_profile" class="form-control" id="profile" value="{{ $product->profile }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="category">Category:</label>
                                            <select name="category_id" class="form-control" id="category">
                                                <option value="">please choose</option>
                                                @foreach($category as $data)
                                                    <option {{ $product->category_id==$data->id?'selected':'' }} value="{{ $data->id }}">{{ $data->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <img width="100%" id="profile-img-tag" src="/images/product/{{ $product->profile }}" alt="{{ $product->profile }}" >
                                    </div>
                                </div>
                                <div class="form-group">
                                    <br>
                                    <br>
                                    <input type="checkbox" name="status" id="status" {{ $product->status?'checked':'' }}>
                                    <label for="status">Status:</label>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('product.index') }}" class="btn btn-danger"> Back</a>
                        <button type="submit" class="btn btn-primary">Submit</button>                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
@endsection

test_1/resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Product Page</div>

                <div class="card-body">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div>
                    @endif
                    <a href="{{ route('product.create') }}" class="btn btn-primary">Add New</a>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>N<sup>0</sup></th>
                                <th>Name</th>
                                <th class="text-center">Price</th>
                                <th>Description</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Profile</th>
                                <th>Category</th>
                                <th>Date</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($records as $record)
                            <tr>
                                <td>{{$record->id}}</td>
                                <td>{{$record->name}}</td>
                                <th class="text-center">{{ number_format($record->price,2) }}</th>
                                <td>{{$record->description}}</td>
                                <td class="text-center">{{$record->status}}</td>
                                <td class="text-center"><img width="50" src="/images/product/thumbnail/{{ $record->profile }}" alt="{{ $record->profile }}" ></td>
                                <td>{{$record->cate_name}}</td>
                                <td>{{$record->created_at}}</td>
                                <td class="text-right">
                                    <form method="post">
                                        @csrf
                                        <a href="{{ route('product.edit', $record->id)}}" class="btn btn-sm btn-warning">Edit</a>
                                        <button onclick="return confirm('are you sure to delete?')" formaction="{{ route('product.destroy', $record->id)}}" type="submit" value="DELETE" name="_method" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $records->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection